name: Publish Docker image to GitHub Package Registry
  
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}
  
env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
  
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      security-events: write
      
    steps:
    
      - name: "actions: Checkout repository"
        id: checkout
        uses: actions/checkout@v2

      - name: "docker: Login to Container Registry"
        id: docker-login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "docker: Extract metadata"
        id: docker-meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}

      - name: "docker: Build image"
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

      - name: "docker: Push Docker image [master branch]"
        id: docker-publish
        if: github.ref_name == 'master'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
